-- vim.api.nvim_create_user_command('TodoListToggle', require('nvim-todo-list').hello, {})
-- vim.api.nvim_create_user_command('CacaUpper', function(opts)
--   print(string.upper(opts.fargs[1]))
-- end, {
--   nargs = 1,
--   complete = function(ArgLead, CmdLine, CursorPos)
--     -- return completion candidates as a list-like table
--     return { 'foo', 'bar', 'baz' }
--   end,
-- })
